platform :ios, '8.0'

# ignore all warnings from all pods
inhibit_all_warnings!
use_frameworks!

def pods
	pod 'iOSBootstrap', '~> 1.5.1'
	pod 'AFNetworking', '~> 2.6'
	pod 'AFNetworkActivityLogger', '~> 2.0'
	pod 'Appirater'
	pod 'PNChart', '0.8.3'
	pod 'SDWebImage'
	pod 'SSKeychain'
	pod 'TMCache'
	pod 'UIColor+FlatColors'
	pod 'libPhoneNumber-iOS',        '~> 0.7.3'
	pod 'CocoaAsyncSocket'
	pod 'HTKDynamicResizingCell'
	pod 'UIImage+ImageCompress'
	pod 'LMMediaPlayer'
	pod 'ArrayUtils'
	pod 'QBImagePickerController'
	pod 'CBStoreHouseRefreshControl'
	pod 'CRToast', '~> 0.0.7'
	pod 'CWStatusBarNotification', '~> 2.3.3'
	pod 'MRProgress'
	pod 'MaterialControls', '~> 1.0.2'
    pod 'AMapLocation' #定位SDK
    pod 'MSWeakTimer', '~> 1.1.0'
    pod 'SCLAlertView-Objective-C'
    pod 'UMengAnalytics-NO-IDFA'
    pod 'Masonry'
end

target '_project_' do
  pods
end